version: '3.8'
services:
  redis-service:
    image: redis:latest
    #para cambiar la memoria es el maxmemory
    #para cambiar la politica de remocion es lo que dice allkeys
    #lo demas no se toca
    command: redis-server --maxmemory 500mb --maxmemory-policy allkeys-lfu
  response-gen:
    build: ./generador_respuestas
    volumes:
      - ./metricas:/app/data
  sistema_cache:
    build: ./sistema_cache
    volumes:
      - ./metricas:/app/data 
    depends_on:
      - redis-service
      - response-gen

  traffic-gen:
    build: ./generador_trafico
    depends_on:
      - sistema_cache
